OAuth
coding-blocks/leads-tracker-backend pull request #12
Opened 2017-08-06 18:41 UTC by bhavyaagg

Fixes #9

2017-08-06 20:16 UTC, championswimmer requested changes

2017-08-06 20:16 UTC, championswimmer commented on src/db/models.ts
> +  , status: {type: Sequelize.ENUM('New','Interested','Uninterested','Enrolled','Untracked'), allowNull: false, defaultValue:'New'}
use all smallcase in the enum options
new, interested . . .

2017-08-06 20:16 UTC, championswimmer commented on src/routers/api/auth.js
> +  // console.log(1)
remove comment

2017-08-06 20:16 UTC, championswimmer commented on public_html/index.html
> +<!DOCTYPE html>
what is the purpose of this file ?

2017-08-12 13:07 UTC, bhavyaagg commented on public_html/index.html
> +<!DOCTYPE html>
Sorry forgot to remove it. It was just for testing the oauth.

2017-08-12 13:16 UTC, bhavyaagg commented
@championswimmer Sir i have updated the pull request.

2017-08-13 17:18 UTC, championswimmer approved these changes

2017-08-13 17:18 UTC, merged